name: swiftcomp
description: A cross-platform composite calculator developed with Flutter, based on SwiftComp, designed for engineers and researchers. Available on iOS, Android, and Web.
publish_to: none

version: 6.2.6+2024122601

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: packages/domain
  data:
    path: packages/data
  infrastructure:
    path: packages/infrastructure

  composite_calculator: ^1.0.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.40.2
  app_tracking_transparency: ^2.0.6
  flutter_math_fork: ^0.7.2
  flutter_staggered_grid_view: ^0.4.1
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  url_launcher: ^6.0.20
  share_plus: ^7.2.2
  linalg: ^0.4.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  provider: ^6.0.2
  flutter_progress_hud: ^2.0.2
  file: ^6.1.4
  flutter_markdown: ^0.7.3+2
  get_it: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  cached_network_image: ^3.3.1
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  flutter_lints: ^3.0.0
#  flutter_native_splash: ^2.3.11
#  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
